# Site settings
title: scoriani - random thoughts on modern systems in the cloud!
email: scoriani@microsoft.com
description: "A learning whiteboard where sketching a lot of ideas around new technologies and experience in distributed computing."
baseurl: ""
url: "https://scoriani.github.io"
twitter_username: scoriani
github_username:  scoriani

# Build settings
markdown: kramdown
permalink: pretty

theme: jekyll-theme-cayman
